// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/sjkyspa/stacks/controller/api/api"
)

type FakeKeyRepository struct {
	UploadStub        func(user api.User, params api.KeyParams) (uploaded api.Key, apiErr error)
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		user   api.User
		params api.KeyParams
	}
	uploadReturns struct {
		result1 api.Key
		result2 error
	}
	GetKeyStub        func(id string) (key api.Key, apiErr error)
	getKeyMutex       sync.RWMutex
	getKeyArgsForCall []struct {
		id string
	}
	getKeyReturns struct {
		result1 api.Key
		result2 error
	}
	GetKeysStub        func() (keys api.Keys, apiErr error)
	getKeysMutex       sync.RWMutex
	getKeysArgsForCall []struct{}
	getKeysReturns     struct {
		result1 api.Keys
		result2 error
	}
	GetKeysForUserStub        func(user api.User) (keys api.Keys, apiErr error)
	getKeysForUserMutex       sync.RWMutex
	getKeysForUserArgsForCall []struct {
		user api.User
	}
	getKeysForUserReturns struct {
		result1 api.Keys
		result2 error
	}
	DeleteStub        func(user api.User, id string) (apiErr error)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		user api.User
		id   string
	}
	deleteReturns struct {
		result1 error
	}
}

func (fake *FakeKeyRepository) Upload(user api.User, params api.KeyParams) (uploaded api.Key, apiErr error) {
	fake.uploadMutex.Lock()
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		user   api.User
		params api.KeyParams
	}{user, params})
	fake.uploadMutex.Unlock()
	if fake.UploadStub != nil {
		return fake.UploadStub(user, params)
	} else {
		return fake.uploadReturns.result1, fake.uploadReturns.result2
	}
}

func (fake *FakeKeyRepository) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *FakeKeyRepository) UploadArgsForCall(i int) (api.User, api.KeyParams) {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return fake.uploadArgsForCall[i].user, fake.uploadArgsForCall[i].params
}

func (fake *FakeKeyRepository) UploadReturns(result1 api.Key, result2 error) {
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 api.Key
		result2 error
	}{result1, result2}
}

func (fake *FakeKeyRepository) GetKey(id string) (key api.Key, apiErr error) {
	fake.getKeyMutex.Lock()
	fake.getKeyArgsForCall = append(fake.getKeyArgsForCall, struct {
		id string
	}{id})
	fake.getKeyMutex.Unlock()
	if fake.GetKeyStub != nil {
		return fake.GetKeyStub(id)
	} else {
		return fake.getKeyReturns.result1, fake.getKeyReturns.result2
	}
}

func (fake *FakeKeyRepository) GetKeyCallCount() int {
	fake.getKeyMutex.RLock()
	defer fake.getKeyMutex.RUnlock()
	return len(fake.getKeyArgsForCall)
}

func (fake *FakeKeyRepository) GetKeyArgsForCall(i int) string {
	fake.getKeyMutex.RLock()
	defer fake.getKeyMutex.RUnlock()
	return fake.getKeyArgsForCall[i].id
}

func (fake *FakeKeyRepository) GetKeyReturns(result1 api.Key, result2 error) {
	fake.GetKeyStub = nil
	fake.getKeyReturns = struct {
		result1 api.Key
		result2 error
	}{result1, result2}
}

func (fake *FakeKeyRepository) GetKeys() (keys api.Keys, apiErr error) {
	fake.getKeysMutex.Lock()
	fake.getKeysArgsForCall = append(fake.getKeysArgsForCall, struct{}{})
	fake.getKeysMutex.Unlock()
	if fake.GetKeysStub != nil {
		return fake.GetKeysStub()
	} else {
		return fake.getKeysReturns.result1, fake.getKeysReturns.result2
	}
}

func (fake *FakeKeyRepository) GetKeysCallCount() int {
	fake.getKeysMutex.RLock()
	defer fake.getKeysMutex.RUnlock()
	return len(fake.getKeysArgsForCall)
}

func (fake *FakeKeyRepository) GetKeysReturns(result1 api.Keys, result2 error) {
	fake.GetKeysStub = nil
	fake.getKeysReturns = struct {
		result1 api.Keys
		result2 error
	}{result1, result2}
}

func (fake *FakeKeyRepository) GetKeysForUser(user api.User) (keys api.Keys, apiErr error) {
	fake.getKeysForUserMutex.Lock()
	fake.getKeysForUserArgsForCall = append(fake.getKeysForUserArgsForCall, struct {
		user api.User
	}{user})
	fake.getKeysForUserMutex.Unlock()
	if fake.GetKeysForUserStub != nil {
		return fake.GetKeysForUserStub(user)
	} else {
		return fake.getKeysForUserReturns.result1, fake.getKeysForUserReturns.result2
	}
}

func (fake *FakeKeyRepository) GetKeysForUserCallCount() int {
	fake.getKeysForUserMutex.RLock()
	defer fake.getKeysForUserMutex.RUnlock()
	return len(fake.getKeysForUserArgsForCall)
}

func (fake *FakeKeyRepository) GetKeysForUserArgsForCall(i int) api.User {
	fake.getKeysForUserMutex.RLock()
	defer fake.getKeysForUserMutex.RUnlock()
	return fake.getKeysForUserArgsForCall[i].user
}

func (fake *FakeKeyRepository) GetKeysForUserReturns(result1 api.Keys, result2 error) {
	fake.GetKeysForUserStub = nil
	fake.getKeysForUserReturns = struct {
		result1 api.Keys
		result2 error
	}{result1, result2}
}

func (fake *FakeKeyRepository) Delete(user api.User, id string) (apiErr error) {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		user api.User
		id   string
	}{user, id})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(user, id)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeKeyRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeKeyRepository) DeleteArgsForCall(i int) (api.User, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].user, fake.deleteArgsForCall[i].id
}

func (fake *FakeKeyRepository) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

var _ api.KeyRepository = new(FakeKeyRepository)
