// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cnupp/appssdk/api"
)

type FakeDomainRepository struct {
	CreateStub        func(params api.DomainParams) (createdDomain api.Domain, apiErr error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		params api.DomainParams
	}
	createReturns struct {
		result1 api.Domain
		result2 error
	}
	GetDomainStub        func(name string) (api.Domain, error)
	getDomainMutex       sync.RWMutex
	getDomainArgsForCall []struct {
		name string
	}
	getDomainReturns struct {
		result1 api.Domain
		result2 error
	}
	GetDomainsStub        func() (api.Domains, error)
	getDomainsMutex       sync.RWMutex
	getDomainsArgsForCall []struct{}
	getDomainsReturns     struct {
		result1 api.Domains
		result2 error
	}
	AttachCertStub        func(api.Domain, api.CertParams) error
	attachCertMutex       sync.RWMutex
	attachCertArgsForCall []struct {
		arg1 api.Domain
		arg2 api.CertParams
	}
	attachCertReturns struct {
		result1 error
	}
	DeleteStub        func(id string) (apiErr error)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		id string
	}
	deleteReturns struct {
		result1 error
	}
	invocations map[string][][]interface{}
}

func (fake *FakeDomainRepository) Create(params api.DomainParams) (createdDomain api.Domain, apiErr error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		params api.DomainParams
	}{params})
	fake.guard("Create")
	fake.invocations["Create"] = append(fake.invocations["Create"], []interface{}{params})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(params)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeDomainRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeDomainRepository) CreateArgsForCall(i int) api.DomainParams {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].params
}

func (fake *FakeDomainRepository) CreateReturns(result1 api.Domain, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 api.Domain
		result2 error
	}{result1, result2}
}

func (fake *FakeDomainRepository) GetDomain(name string) (api.Domain, error) {
	fake.getDomainMutex.Lock()
	fake.getDomainArgsForCall = append(fake.getDomainArgsForCall, struct {
		name string
	}{name})
	fake.guard("GetDomain")
	fake.invocations["GetDomain"] = append(fake.invocations["GetDomain"], []interface{}{name})
	fake.getDomainMutex.Unlock()
	if fake.GetDomainStub != nil {
		return fake.GetDomainStub(name)
	} else {
		return fake.getDomainReturns.result1, fake.getDomainReturns.result2
	}
}

func (fake *FakeDomainRepository) GetDomainCallCount() int {
	fake.getDomainMutex.RLock()
	defer fake.getDomainMutex.RUnlock()
	return len(fake.getDomainArgsForCall)
}

func (fake *FakeDomainRepository) GetDomainArgsForCall(i int) string {
	fake.getDomainMutex.RLock()
	defer fake.getDomainMutex.RUnlock()
	return fake.getDomainArgsForCall[i].name
}

func (fake *FakeDomainRepository) GetDomainReturns(result1 api.Domain, result2 error) {
	fake.GetDomainStub = nil
	fake.getDomainReturns = struct {
		result1 api.Domain
		result2 error
	}{result1, result2}
}

func (fake *FakeDomainRepository) GetDomains() (api.Domains, error) {
	fake.getDomainsMutex.Lock()
	fake.getDomainsArgsForCall = append(fake.getDomainsArgsForCall, struct{}{})
	fake.guard("GetDomains")
	fake.invocations["GetDomains"] = append(fake.invocations["GetDomains"], []interface{}{})
	fake.getDomainsMutex.Unlock()
	if fake.GetDomainsStub != nil {
		return fake.GetDomainsStub()
	} else {
		return fake.getDomainsReturns.result1, fake.getDomainsReturns.result2
	}
}

func (fake *FakeDomainRepository) GetDomainsCallCount() int {
	fake.getDomainsMutex.RLock()
	defer fake.getDomainsMutex.RUnlock()
	return len(fake.getDomainsArgsForCall)
}

func (fake *FakeDomainRepository) GetDomainsReturns(result1 api.Domains, result2 error) {
	fake.GetDomainsStub = nil
	fake.getDomainsReturns = struct {
		result1 api.Domains
		result2 error
	}{result1, result2}
}

func (fake *FakeDomainRepository) AttachCert(arg1 api.Domain, arg2 api.CertParams) error {
	fake.attachCertMutex.Lock()
	fake.attachCertArgsForCall = append(fake.attachCertArgsForCall, struct {
		arg1 api.Domain
		arg2 api.CertParams
	}{arg1, arg2})
	fake.guard("AttachCert")
	fake.invocations["AttachCert"] = append(fake.invocations["AttachCert"], []interface{}{arg1, arg2})
	fake.attachCertMutex.Unlock()
	if fake.AttachCertStub != nil {
		return fake.AttachCertStub(arg1, arg2)
	} else {
		return fake.attachCertReturns.result1
	}
}

func (fake *FakeDomainRepository) AttachCertCallCount() int {
	fake.attachCertMutex.RLock()
	defer fake.attachCertMutex.RUnlock()
	return len(fake.attachCertArgsForCall)
}

func (fake *FakeDomainRepository) AttachCertArgsForCall(i int) (api.Domain, api.CertParams) {
	fake.attachCertMutex.RLock()
	defer fake.attachCertMutex.RUnlock()
	return fake.attachCertArgsForCall[i].arg1, fake.attachCertArgsForCall[i].arg2
}

func (fake *FakeDomainRepository) AttachCertReturns(result1 error) {
	fake.AttachCertStub = nil
	fake.attachCertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDomainRepository) Delete(id string) (apiErr error) {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		id string
	}{id})
	fake.guard("Delete")
	fake.invocations["Delete"] = append(fake.invocations["Delete"], []interface{}{id})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(id)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeDomainRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeDomainRepository) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].id
}

func (fake *FakeDomainRepository) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDomainRepository) Invocations() map[string][][]interface{} {
	return fake.invocations
}

func (fake *FakeDomainRepository) guard(key string) {
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
}

var _ api.DomainRepository = new(FakeDomainRepository)
