// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/sjkyspa/stacks/controller/api/api"
)

type FakeUserRepository struct {
	CreateStub        func(params api.UserParams) (createdUser api.User, apiErr error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		params api.UserParams
	}
	createReturns struct {
		result1 api.User
		result2 error
	}
	GetUserStub        func(id string) (api.User, error)
	getUserMutex       sync.RWMutex
	getUserArgsForCall []struct {
		id string
	}
	getUserReturns struct {
		result1 api.User
		result2 error
	}
	GetUserByEmailStub        func(email string) (api.Users, error)
	getUserByEmailMutex       sync.RWMutex
	getUserByEmailArgsForCall []struct {
		email string
	}
	getUserByEmailReturns struct {
		result1 api.Users
		result2 error
	}
}

func (fake *FakeUserRepository) Create(params api.UserParams) (createdUser api.User, apiErr error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		params api.UserParams
	}{params})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(params)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeUserRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeUserRepository) CreateArgsForCall(i int) api.UserParams {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].params
}

func (fake *FakeUserRepository) CreateReturns(result1 api.User, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 api.User
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) GetUser(id string) (api.User, error) {
	fake.getUserMutex.Lock()
	fake.getUserArgsForCall = append(fake.getUserArgsForCall, struct {
		id string
	}{id})
	fake.getUserMutex.Unlock()
	if fake.GetUserStub != nil {
		return fake.GetUserStub(id)
	} else {
		return fake.getUserReturns.result1, fake.getUserReturns.result2
	}
}

func (fake *FakeUserRepository) GetUserCallCount() int {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	return len(fake.getUserArgsForCall)
}

func (fake *FakeUserRepository) GetUserArgsForCall(i int) string {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	return fake.getUserArgsForCall[i].id
}

func (fake *FakeUserRepository) GetUserReturns(result1 api.User, result2 error) {
	fake.GetUserStub = nil
	fake.getUserReturns = struct {
		result1 api.User
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) GetUserByEmail(email string) (api.Users, error) {
	fake.getUserByEmailMutex.Lock()
	fake.getUserByEmailArgsForCall = append(fake.getUserByEmailArgsForCall, struct {
		email string
	}{email})
	fake.getUserByEmailMutex.Unlock()
	if fake.GetUserByEmailStub != nil {
		return fake.GetUserByEmailStub(email)
	} else {
		return fake.getUserByEmailReturns.result1, fake.getUserByEmailReturns.result2
	}
}

func (fake *FakeUserRepository) GetUserByEmailCallCount() int {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	return len(fake.getUserByEmailArgsForCall)
}

func (fake *FakeUserRepository) GetUserByEmailArgsForCall(i int) string {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	return fake.getUserByEmailArgsForCall[i].email
}

func (fake *FakeUserRepository) GetUserByEmailReturns(result1 api.Users, result2 error) {
	fake.GetUserByEmailStub = nil
	fake.getUserByEmailReturns = struct {
		result1 api.Users
		result2 error
	}{result1, result2}
}

var _ api.UserRepository = new(FakeUserRepository)
